# Este es un flujo de trabajo básico para ayudarlo a comenzar con Actions

name: CI

#Controla cuándo se ejecutará el flujo de trabajo
on:
  # Activa el flujo de trabajo en eventos de solicitud de inserción o extracción, pero solo para la rama principal
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  #  Le permite ejecutar este flujo de trabajo manualmente desde la pestaña Acciones
  workflow_dispatch:

# Una ejecución de flujo de trabajo se compone de uno o más trabajos que pueden ejecutarse secuencialmente o en paralelo
jobs:
  #  Este flujo de trabajo contiene un solo trabajo llamado "compilación"
  build:
    # El tipo de corredor en el que se ejecutará el trabajo
    runs-on: ubuntu-latest

    # Los pasos representan una secuencia de tareas que se ejecutarán como parte del trabajo.
    steps:
      # Chequea tu repositorio en $GITHUB_WORKSPACE, para que tu trabajo pueda acceder a el
      - uses: actions/checkout@v2

      # Ejecuta un solo comando usando el shell de los corredores
      - name: Run a one-line script
        run: echo Hola mundo v2!

      # Ejecuta un conjunto de comandos usando el shell de los corredores.
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      # Ejecutar la cobertura
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2.5.0
        with:
          generate-branches-badge: true          
